### ISSUE TITLE
stash & pop

### ISSUE THREAD

**Issue by jgollenz** [entwicklerkollektiv-wien/wiener-git#6]
Zeilen 16 und 17 in `wiener-git.plugin.zsh`:
 ```
stash) git_command+=(wegmitdemschaß);;
pop) git_command+=(retour);;
```

Kann es sein, dass hier die Case Evaluation und dementsprechende Branch verwechselt wurden? Bei allen anderen ist es umgekehrt

**Comment by andiwi** [comment]
ja da hast du recht! Bitte gerne einen PR erstellen. Ansonsten fixe ich es nächstes Wochenende.

**Comment by jgollenz** [comment]
PR ist raus

**Comment by andiwi** [comment]
danke!
